# Copyright 2017 JanusGraph Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# In general, set the timeouts to twice the usual execution time for the compute type.
# 480 minutes is the maximum build time now.
#
defaultComputeImage: maven:3-jdk-8
defaultComputeType: BUILD_GENERAL1_LARGE
defaultPrivilegedMode: true
pipelines:
- name: j1
  parallelBuildActions:
  - name: bdb
    timeout: 30
    env:
    - name: MODULE
      value: janusgraph-berkeleyje
  - name: h-l-s
    timeout: 42
    env:
    - name: MODULE
      value: janusgraph-hadoop,janusgraph-lucene,janusgraph-solr
  - name: cassandra
    timeout: 220
    env:
    - name: MODULE
      value: janusgraph-cassandra
  - name: test
    timeout: 43
    env:
    - name: MODULE
      value: janusgraph-test
- name: j2
  parallelBuildActions:
  - name: hbase098
    timeout: 130
    env:
    - name: MODULE
      value: janusgraph-hbase-parent/janusgraph-hbase-098
  - name: hbase10
    timeout: 79
    env:
    - name: MODULE
      value: janusgraph-hbase-parent/janusgraph-hbase-10
  - name: es
    timeout: 100
    computeImage: docker:dind
    env:
    - name: MODULE
      value: janusgraph-es
  - name: cql
    timeout: 118
    env:
    - name: MODULE
      value: janusgraph-cql
