version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  labels:
    - "backport"
    - "backport/v0.6"
    - "dependencies"
    - "java"

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  labels:
    - "backport"
    - "backport/v0.6"
    - "dependencies"