version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.spotify:docker-maven-plugin
    versions:
    - "> 0.4.13"
  - dependency-name: com.thoughtworks.paranamer:paranamer
    versions:
    - "> 2.6"
  - dependency-name: org.apache.hbase:hbase-server
    versions:
    - ">= 2.a, < 3"
  - dependency-name: org.apache.hbase:hbase-shaded-client
    versions:
    - ">= 2.a, < 3"
  - dependency-name: org.apache.lucene:lucene-spatial
    versions:
    - ">= 8.a, < 9"
  - dependency-name: io.netty:netty-transport-native-epoll
    versions:
    - 4.1.60.Final
  - dependency-name: io.netty:netty-buffer
    versions:
    - 4.1.60.Final
  - dependency-name: io.netty:netty-transport
    versions:
    - 4.1.60.Final
  - dependency-name: io.netty:netty-codec
    versions:
    - 4.1.60.Final
  - dependency-name: io.netty:netty-resolver
    versions:
    - 4.1.60.Final
  - dependency-name: io.netty:netty-common
    versions:
    - 4.1.60.Final
  - dependency-name: io.netty:netty-handler
    versions:
    - 4.1.60.Final
  - dependency-name: io.netty:netty-all
    versions:
    - 4.1.60.Final
  - dependency-name: com.google.errorprone:error_prone_annotations
    versions:
    - 2.5.1
  - dependency-name: com.google.cloud.bigtable:bigtable-hbase-2.x-shaded
    versions:
    - 1.19.0
    - 1.19.1
  - dependency-name: io.dropwizard.metrics:metrics-jmx
    versions:
    - 4.1.18
  - dependency-name: io.dropwizard.metrics:metrics-graphite
    versions:
    - 4.1.18
  - dependency-name: io.dropwizard.metrics:metrics-jvm
    versions:
    - 4.1.18
  - dependency-name: io.dropwizard.metrics:metrics-core
    versions:
    - 4.1.18
  - dependency-name: com.google.protobuf:protobuf-java-util
    versions:
    - 3.15.0
    - 3.15.3
  - dependency-name: com.google.protobuf:protobuf-java
    versions:
    - 3.15.0
    - 3.15.3
  - dependency-name: org.apache.solr:solr-test-framework
    versions:
    - 8.7.0
    - 8.8.0
  - dependency-name: org.apache.solr:solr-solrj
    versions:
    - 8.7.0
    - 8.8.0
  - dependency-name: org.apache.lucene:lucene-spatial-extras
    versions:
    - 8.7.0
    - 8.8.0
  - dependency-name: org.apache.lucene:lucene-queryparser
    versions:
    - 8.7.0
    - 8.8.0
  - dependency-name: org.apache.lucene:lucene-analyzers-common
    versions:
    - 8.7.0
    - 8.8.0
  - dependency-name: org.apache.lucene:lucene-core
    versions:
    - 8.7.0
    - 8.8.0
  - dependency-name: org.elasticsearch.client:elasticsearch-rest-client
    versions:
    - 7.11.0
  - dependency-name: org.junit.platform:junit-platform-runner
    versions:
    - 1.7.1
  - dependency-name: org.junit.platform:junit-platform-launcher
    versions:
    - 1.7.1
  - dependency-name: com.github.jbellis:jamm
    versions:
    - 0.3.3
  - dependency-name: org.locationtech.jts:jts-core
    versions:
    - 1.18.0
  - dependency-name: org.apache.tinkerpop:spark-gremlin
    versions:
    - 3.4.10
  - dependency-name: org.apache.tinkerpop:hadoop-gremlin
    versions:
    - 3.4.10
  - dependency-name: org.apache.tinkerpop:tinkergraph-gremlin
    versions:
    - 3.4.10
  - dependency-name: org.apache.tinkerpop:gremlin-test
    versions:
    - 3.4.10
  - dependency-name: org.apache.tinkerpop:gremlin-driver
    versions:
    - 3.4.10
  - dependency-name: org.apache.tinkerpop:gremlin-groovy
    versions:
    - 3.4.10
  - dependency-name: org.apache.tinkerpop:gremlin-console
    versions:
    - 3.4.10
  - dependency-name: org.apache.tinkerpop:gremlin-server
    versions:
    - 3.4.10
  - dependency-name: org.apache.tinkerpop:gremlin-core
    versions:
    - 3.4.10
