# Copyright 2017 JanusGraph Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
version: 0.1
env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-1.8-openjdk"
phases:
  install:
    commands:
      - if [ "$MODULE" = "janusgraph-es" ]; then nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay& fi
      - if [ "$MODULE" = "janusgraph-es" ]; then timeout -t 15 sh -c "until docker info; do echo .; sleep 1; done"; fi
      - if [ "$MODULE" = "janusgraph-es" ]; then apk --update add openjdk8 maven; fi
  build:
    commands:
      - echo Build started on `date`
      - mvn install --update-snapshots --threads 2.0C --batch-mode -DskipTests=true -Dmaven.javadoc.skip=true -Dmaven.compiler.showWarnings=false
      - chmod -R a+x ./janusgraph-hbase-parent/janusgraph-hbase-098/bin && chmod -R a+x ./janusgraph-hbase-parent/janusgraph-hbase-10/bin
      - mvn verify --projects $MODULE $ARGS
      - mvn surefire-report:report --projects $MODULE
  post_build:
    commands:
      - echo Build completed on `date`
      - mkdir -p results/mvn
      - echo "$MODULE" | tr "," "\n" | while read MOD; do if [ -d "${MOD}/target" ]; then mkdir -p results/mvn/${MOD} && cp -r ${MOD}/target results/mvn/${MOD}; fi; done
artifacts:
  base-directory: results
  files:
    - mvn/**/*
