# Don't post a comment on pull requests.
comment: off

# Disable commit statuses
coverage:
  status:
    project: no
    patch: no
    changes: no

# Ignore test files
ignore:
  - "**/test/.*"
  - "janusgraph-test/**"

