# Don't post a comment on pull requests.
comment: false

# Disable commit statuses
coverage:
  status:
    project:
      default: false
    patch:
      default: false
    changes:
      default: false

# Ignore test files
ignore:
  - "**/test/.*"
  - "janusgraph-test/**"

