[[connecting-via-java]]
== Connecting from Java

JanusGraph can be queried from a Java application with Apache TinkerPop's https://tinkerpop.apache.org/docs/{tinkerpop_version}/reference/#connecting-via-java[Gremlin Driver].
While it is possible to embed JanusGraph as a library inside a Java application and then directly connect to the backend, this section assumes that the application connects to JanusGraph Server.
For information on how to embed JanusGraph, see the https://github.com/JanusGraph/janusgraph/tree/master/janusgraph-examples[JanusGraph Examples projects].

This section only covers how applications can connect to JanusGraph Server.
Refer to <<gremlin>> for an introduction to Gremlin and pointers to further resources.

=== Getting Started with JanusGraph and Gremlin-Java

To get started with JanusGraph in Java:

. Create an application with Maven:
+
[source, bash]
----
mvn archetype:generate -DgroupId=com.mycompany.project
   -DartifactId=gremlin-example
   -DarchetypeArtifactId=maven-archetype-quickstart 
   -DinteractiveMode=false
----

. Add dependencies on `janusgraph-core` and `gremlin-driver` to the `pom.xml` file:
+
[source, xml]
----
...
<dependencies>
  <dependency>
    <groupId>org.janusgraph</groupId>
    <artifactId>janusgraph-core</artifactId>
    <version>$MAVEN{project.version}</version>
  </dependency>
  <dependency>
    <groupId>org.apache.tinkerpop</groupId>
    <artifactId>gremlin-driver</artifactId>
    <version>$MAVEN{tinkerpop.version}</version>
  </dependency>
...
</dependencies>
...
----

. Add two configuration files, `conf/remote-graph.properties` and `conf/remote-objects.yaml`:
+
.conf/remote-graph.properties
[source, changelog]
----
gremlin.remote.remoteConnectionClass=org.apache.tinkerpop.gremlin.driver.remote.DriverRemoteConnection
gremlin.remote.driver.clusterFile=conf/remote-objects.yaml
gremlin.remote.driver.sourceName=g
----
+
.conf/remote-objects.yaml
[source, yaml]
----
hosts: [localhost]
port: 8182
serializer: { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV1d0,
              config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry] }}
----

. Create a `GraphTraversalSource` which is the basis for all Gremlin traversals:
+
[source, java]
----
Graph graph = EmptyGraph.instance();
GraphTraversalSource g = graph.traversal().withRemote("conf/remote-graph.properties");
// Reuse 'g' across the application
// and close it on shut-down to close open connections with g.close()
----

. Execute a simple traversal:
+
[source, java]
----
Object herculesAge = g.V().has("name", "hercules").values("age").next();
System.out.println("Hercules is " + herculesAge + " years old.");
----
+
`next()` is a terminal step that submits the traversal to the Gremlin Server and returns a single result.
Other terminal steps can be found https://tinkerpop.apache.org/docs/{tinkerpop_version}/reference/#terminal-steps[in TinkerPop's reference documentation].

=== JanusGraph Specific Types and Predicates

JanusGraph specific types and <<search-predicates, predicates>> can be used directly from a Java application through the dependency `janusgraph-core`.
