[[upgrade]]
[appendix]
== Upgrade Instructions

Please follow these instructions when upgrading from Titan or an older
JanusGraph release.

=== Upgrading from Titan 1.0.0, 1.1.0-SNAPSHOT

JanusGraph is based on the latest commit to the `titan11` branch of
https://github.com/thinkaurelius/titan[Titan repo].

JanusGraph has made the following changes to Titan, so you will need to adjust
your code and configuration accordingly:

. module names: `titan-*` are now `janusgraph-*`
. package names: `com.thinkaurelius.titan` are now `org.janusgraph`
. class names: `Titan*` are now `JanusGraph*` except in cases where this would
  duplicate a word, e.g., `TitanGraph` is simply `JanusGraph` rather than
  `JanusGraphGraph`

*IMPORTANT* If you are pointing JanusGraph at an existing Titan database you will
need to set the `graph.titan-version` property. For more information on how to
configure JanusGraph to read data which had previously been written by Titan
refer to <<migrating-titan>>.

=== Upgrading from JanusGraph 0.1.z

==== Elasticsearch

JanusGraph 0.1.z is compatible with Elasticsearch 1.5.z. There were several
configuration options available, including transport client, node client, and
legacy configuration track. JanusGraph 0.2.0 is compatible with Elasticsearch
versions from 1.y through 6.y, however it offers only a single configuration
option using the REST client.

===== Transport client

The `TRANSPORT_CLIENT` interface has been replaced with `REST_CLIENT`. When
migrating an existing graph to JanusGraph 0.2.0, the `interface` property must
be set when connecting to the graph:

[source, properties]
----
index.search.backend=elasticsearch
index.search.elasticsearch.interface=REST_CLIENT
index.search.hostname=127.0.0.1
----

After connecting to the graph, the property update can be made permanent by
making the change with `JanusGraphManagement`:

[source, gremlin]
----
mgmt = graph.openManagement()
mgmt.set("index.search.elasticsearch.interface", "REST_CLIENT")
mgmt.commit()
----

===== Node client

A node client with JanusGraph can be configured in a few ways. If the node
client was configured as a client-only or non-data node, follow the steps
from the <<_transport_client, transport client>> section to connect to the
existing cluster using the `REST_CLIENT` instead. If the node client was
a data node (local-mode), then convert it into a standalone Elasticsearch
node, running in a separate JVM from your application process. This can be
done by using the node's configuration from the JanusGraph configuration to
start a standalone Elasticsearch 1.5.z node. For example, we start with these
JanusGraph 0.1.z properties:

[source, properties]
----
index.search.backend=elasticsearch
index.search.elasticsearch.interface=NODE
index.search.conf-file=es-client.yml
index.search.elasticsearch.ext.node.name=alice
----

where the configuration file `es-client.yml` has properties:

[source, yaml]
----
node.data: true
path.data: /var/lib/elasticsearch/data
path.work: /var/lib/elasticsearch/work
path.logs: /var/log/elasticsearch
----

The properties found in the configuration file `es-client.yml` and the
`index.search.elasticsearch.ext.*` properties can be inserted into `$ES_HOME/config/elasticsearch.yml`
so that a standalone Elasticsearch 1.5.z node can be started with the same
properties. Keep in mind that if any `path` locations have relative paths,
those values may need to be updated appropriately. Once the standalone
Elasticsearch node is started, follow the directions in the <<_transport_client, transport client>>
section to complete the migration to the `REST_CLIENT` interface. Note that
the `index.search.conf-file` and `index.search.elasticsearch.ext.*` properties
are not used by the `REST_CLIENT` interface, so they can be removed from the
configuration properties.

===== Legacy configuration

The legacy configuration track was not recommended in JanusGraph 0.1.z and is
no longer supported in JanusGraph 0.2.0. Users should refer to the previous
sections and migrate to the `REST_CLIENT`.
