[[version-compat]]
[appendix]
== Version Compatibility

The JanusGraph project is growing along with the rest of the graph and big data
ecosystem and utilized storage and indexing backends. Below are version
compatibilities between the various versions of components. For dependent
backend systems, different minor versions are typically supported as well. It is
strongly encouraged to verify version compatibility prior to deploying
JanusGraph.

Although JanusGraph may be compatible with older and no longer supported
versions of its dependencies, users are warned that there are possible risks
and security exposures with running software that is no longer supported or
updated. Please check with the software providers to understand their supported
versions. Users are strongly encouraged to use the latest versions of the
software.

.Version Compatibility Matrix
[options="header"]
|==========================
| JanusGraph | Cassandra | HBase | Bigtable | Elasticsearch | Solr | TinkerPop | Spark | Scala
| 0.1.0 | 1.2.z, 2.0.z, 2.1.z | 0.98.z, 1.0.z, 1.1.z, 1.2.z | 0.9.z, 1.0.0-preZ, 1.0.0 | 1.5.z |  5.2.z | 3.2.z | 1.6.z | 2.10.z
| 0.1.1 | 1.2.z, 2.0.z, 2.1.z | 0.98.z, 1.0.z, 1.1.z, 1.2.z | 0.9.z, 1.0.0-preZ, 1.0.0 | 1.5.z |  5.2.z | 3.2.z | 1.6.z | 2.10.z
| 0.2.0 | 1.2.z, 2.0.z, 2.1.z, 2.2.z, 3.0.z, 3.11.z | 0.98.z, 1.0.z, 1.1.z, 1.2.z, 1.3.z | 0.9.z, 1.0.0-preZ, 1.0.0 | 1.5-1.7.z, 2.3-2.4.z, 5.y, 6.y |  5.2-5.5.z, 6.2-6.6.z, 7.y | 3.2.z | 1.6.z | 2.10.z
|==========================

