# Copyright 2023 JanusGraph Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CI Backend ScyllaDB

on:
  pull_request:
    paths-ignore:
    - 'docs/**'
    - '.github/workflows/ci-docs.yml'
    - '.github/ISSUE_TEMPLATE/**'
    - 'requirements.txt'
    - 'mkdocs.yml'
    - 'docs.Dockerfile'
    - '*.md'
  push:
    paths-ignore:
    - 'docs/**'
    - '.github/workflows/ci-docs.yml'
    - '.github/ISSUE_TEMPLATE/**'
    - 'requirements.txt'
    - 'mkdocs.yml'
    - 'docs.Dockerfile'
    - '*.md'
    branches-ignore:
      - 'dependabot/**'

env:
  BUILD_MAVEN_OPTS: "-DskipTests=true --batch-mode --also-make"
  VERIFY_MAVEN_OPTS: "-Pcoverage"

jobs:
  build-all:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: zulu
      - run: mvn clean install --projects janusgraph-all -Pjanusgraph-cache -Dmaven.javadoc.skip=true ${{ env.BUILD_MAVEN_OPTS }}
      - run: mvn verify --projects janusgraph-all -Pjanusgraph-cache ${{ env.VERIFY_MAVEN_OPTS }}

  tests:
    runs-on: ubuntu-22.04
    needs: build-all
    strategy:
      fail-fast: false
      matrix:
        include:
          - module: scylla
            args: "-Pscylla-murmur -Dtest=\"**/diskstorage/cql/*\""
            name: murmur-diskstorage
            java: 8
          - module: scylla
            args: "-Pscylla-murmur -Dtest=\"**/graphdb/cql/*\""
            name: murmur-graphdb
            java: 8
          - module: scylla
            args: "-Pscylla-murmur -Dtest=\"**/hadoop/*\""
            name: murmur-hadoop
            java: 8
          - module: scylla
            args: "-Pscylla-murmur -Dtest=\"**/core/cql/*\""
            name: murmur-core
            java: 8
        # FIXME: this test is failing due to problems with ScyllaDB startup for Testcontainers. Issue: https://github.com/JanusGraph/janusgraph/issues/3595
        #  - module: scylla
        #    args: "-Pscylla-murmur-ssl -Dtest=\"**/diskstorage/cql/CQLStoreTest.java\""
        #    name: murmur-ssl
        #    java: 8
        # FIXME: this test is failing due to problems with ScyllaDB startup for Testcontainers. Issue: https://github.com/JanusGraph/janusgraph/issues/3595
        #  - module: scylla
        #    args: "-Pscylla-murmur-client-auth -Dtest=\"**/diskstorage/cql/CQLStoreTest.java\""
        #    name: murmur-client-auth
        #    java: 8
          - module: scylla
            args: "-Pscylla-murmur -Dtest=\"**/diskstorage/cql/*\""
            name: murmur-diskstorage
            install-args: "-Pjava-11"
            java: 11
          - module: scylla
            args: "-Pscylla-murmur -Dtest=\"**/graphdb/cql/*\""
            name: murmur-graphdb
            install-args: "-Pjava-11"
            java: 11
          - module: scylla
            args: "-Pscylla-murmur -Dtest=\"**/hadoop/*\""
            name: murmur-hadoop
            install-args: "-Pjava-11"
            java: 11
          - module: scylla
            args: "-Pscylla-murmur -Dtest=\"**/core/cql/*\""
            name: murmur-core
            install-args: "-Pjava-11"
            java: 11
        # FIXME: this test is failing due to problems with ScyllaDB startup for Testcontainers. Issue: https://github.com/JanusGraph/janusgraph/issues/3595
        #  - module: scylla
        #    args: "-Pscylla-murmur-ssl -Dtest=\"**/diskstorage/cql/CQLStoreTest.java\""
        #    name: murmur-ssl
        #    install-args: "-Pjava-11"
        #    java: 11
        # FIXME: this test is failing due to problems with ScyllaDB startup for Testcontainers. Issue: https://github.com/JanusGraph/janusgraph/issues/3595
        #  - module: scylla
        #    args: "-Pscylla-murmur-client-auth -Dtest=\"**/diskstorage/cql/CQLStoreTest.java\""
        #    name: murmur-client-auth
        #    install-args: "-Pjava-11"
        #    java: 11
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: zulu
      - run: mvn clean install --projects janusgraph-${{ matrix.module }} ${{ env.BUILD_MAVEN_OPTS }} ${{ matrix.install-args }}
      - run: mvn verify --projects janusgraph-${{ matrix.module }} ${{ env.VERIFY_MAVEN_OPTS }} ${{ matrix.install-args }} ${{ matrix.args }}
      - uses: actions/upload-artifact@v3
        with:
          name: jacoco-reports
          path: target/jacoco-combined.exec
      - uses: codecov/codecov-action@v3
        with:
          name: codecov-cql-${{ matrix.name }}-java-${{ matrix.java }}
