# Copyright 2020 JanusGraph Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Tinkerpop Tests

on:
  pull_request:
    paths-ignore:
    - 'docs/**'
  push:
    paths-ignore:
    - 'docs/**'

env:
  ES_JAVA_OPTS: "-Xms256m -Xmx512m"

jobs:
  build-all:
    runs-on: ubuntu-20.04
    if: "contains(github.event.head_commit.message, '[tp-tests]')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: mvn clean install --projects janusgraph-all --also-make 
          -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode

  tp-tests:
    runs-on: ubuntu-20.04
    if: "contains(github.event.head_commit.message, '[tp-tests]')"
    needs: build-all
    strategy:
      fail-fast: false
      matrix:
        include:
          - module: inmemory
            args: "-Dtest.skip.tp=false -DskipTests=true"
          - module: berkeleyje
            args: "-Dtest.skip.tp=false -DskipTests=true"
          - module: cql
            args: "-Pcassandra3-byteordered -Dtest.skip.tp=false -DskipTests=true"
          - module: cql
            args: "-Pcassandra3-murmur -Dtest.skip.tp=false -DskipTests=true"
          - module: hbase-parent/janusgraph-hbase-10
            args: "-Dtest.skip.tp=false -DskipTests=true"
          - module: hbase-parent/janusgraph-hbase-10
            install-args: "-Dhbase.profile -Phbase2"
            args: "-Dtest.skip.tp=false -DskipTests=true"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: mvn clean install --projects janusgraph-${{ matrix.module }} --also-make 
          -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode ${{ matrix.install-args }}
      - run: mvn verify --projects janusgraph-${{ matrix.module }} ${{ matrix.args }}
